version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: resume-matcher-api:latest
    container_name: resume-matcher-api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL_NAME=llama-3.3-70b-versatile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped
